#!/usr/bin/env bash
# Configure custom 404 page not found Error page

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

str_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s#server_name _;#$str_to_replace#" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

str_to_replace="listen 80 default_server;\\
\\
\\terror_page 404 /404.html;\\
\\tlocation = /404.html {\\
\\t\\troot /var/www/html;\\
\\t\\tinternal;\\
\\t}"

sudo sed -i "s#listen 80 default_server;#$str_to_replace#" /etc/nginx/sites-enabled/default

sudo service nginx restart
