#!/usr/bin/env bash
# install haproxy
sudo apt-get update
sudo apt-get install -y haproxy

echo "
listen my_servers
        bind *:80
        balance roundrobin
        mode http
        server 445380-web-01 3.83.227.31:80 check
        server 445380-web-02 100.25.33.238:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
